export const SYSTEM_MESSAGE = {
  VALIDATION_ERROR: 'Lỗi dữ liệu đầu vào'
} as const

export const AUTHENTICATE_MESSAGE = {
  ACCESS_TOKEN_IS_REQUIRED: 'Không được bỏ trống Access token',
  ACCESS_TOKEN_MUST_BE_A_STRING: 'Access token phải là một chuỗi ký tự',
  ACCESS_TOKEN_INVALID: 'Access token không hợp lệ',
  USER_DOES_NOT_EXIST: 'Người dùng không tồn tại',
  REFRESH_TOKEN_IS_REQUIRED: 'Không được bỏ trống Refresh token',
  REFRESH_TOKEN_MUST_BE_A_STRING: 'Refresh token phải là một chuỗi ký tự',
  REFRESH_TOKEN_INVALID: 'Refresh token không hợp lệ',
  AUTHENTICATION_FAILED: 'Yêu cầu xác thực trước khi thực hiện hành động này',
  YOU_DONT_HAVE_PERMISSION_TO_DO_THIS: 'Bạn không có quyền làm điều này',
  TOKEN_PAIR_MISMATCH: 'Mã xác thực không hợp lệ'
} as const

export const USER_MESSAGE = {
  REGISTER_SUCCESS: 'Đăng ký tài khoản thành công',
  REGISTER_FAILURE: 'Đăng ký tài khoản thất bại',
  LOGIN_SUCCESS: 'Đăng nhập tài khoản thành công',
  LOGIN_FAILURE: 'Đăng nhập tài khoản thất bại',
  LOGOUT_SUCCESS: 'Đăng xuất tài khoản thành công',
  LOGOUT_FAILURE: 'Đăng xuất tài khoản thất bại',
  VERIFY_TOKEN_SUCCESS: 'Xác minh mã xác minh thành công',
  VERIFY_TOKEN_FAILURE: 'Xác minh mã xác minh thất bại',
  GET_USER_INFOMATION_SUCCESS: 'Lấy thông tin tài khoản thành công',
  GET_USER_INFOMATION_FAILURE: 'Lấy thông tin tài khoản thất bại',
  TOKEN_IS_REQUIRED: 'Không được bỏ trống mã xác thực',
  TOKEN_MUST_BE_A_STRING: 'Mã xác thực phải là chuỗi ký tự',
  TOKEN_LENGTH_MUST_BE_FROM_1_TO_50: 'Mã xác thực phải có độ dài từ 1 đến 1000 ký tự',
  INVALID_TOKEN: 'Mã xác thực không hợp lệ',
  NAME_IS_REQUIRED: 'Không được bỏ trống tên người dùng',
  NAME_MUST_BE_A_STRING: 'Tên người dùng phải là chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_50: 'Tên người dùng phải có độ dài từ 1 đến 50 ký tự',
  EMAIL_IS_REQUIRED: 'Không được bỏ trống địa chỉ email',
  EMAIL_MUST_BE_A_STRING: 'Địa chỉ email phải là một chuỗi ký tự',
  EMAIL_LENGTH_MUST_BE_FROM_5_TO_100: 'Địa chỉ email phải có độ dài từ 5 đến 100 ký tự',
  EMAIL_IS_NOT_VALID: 'Địa chỉ email không đúng định dạng',
  EMAIL_ALREADY_EXISTS: 'Địa chỉ email đã được sử dụng',
  PASSWORD_IS_REQUIRED: 'Không được bỏ trống mật khẩu',
  PASSWORD_MUST_BE_A_STRING: 'Mật khẩu phải là một chuỗi ký tự',
  PASSWORD_LENGTH_MUST_BE_FROM_8_TO_100: 'Mật khẩu phải có độ dài từ 8 đến 100 ký tự',
  PASSWORD_MUST_BE_STRONG: 'Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Không được bỏ trống xác nhận mật khẩu',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Xác nhận mật khẩu phải là một chuỗi ký tự',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_100: 'Xác nhận mật khẩu phải có độ dài từ 8 đến 100 ký tự',
  CONFIRM_PASSWORD_MUST_BE_STRONG:
    'Xác nhận mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
  CONFIRM_PASSWORD_DOES_NOT_MATCH_PASSWORD: 'Xác nhận mật khẩu phải khớp với mật khẩu',
  INCORRECT_EMAIL_OR_PASSWORD: 'Địa chỉ email hoặc mật khẩu không chính xác'
}

export const CATEGORY_MESSAGE = {
  GET_CATEGORY_SUCCESS: 'Lấy thông tin danh mục thành công',
  GET_CATEGORY_FAILURE: 'Lấy thông tin danh mục thất bại',
  CREATE_CATEGORY_SUCCESS: 'Tạo danh mục thành công',
  CREATE_CATEGORY_FAILURE: 'Tạo danh mục thất bại',
  UPDATE_CATEGORY_SUCCESS: 'Cập nhật danh mục thành công',
  UPDATE_CATEGORY_FAILURE: 'Cập nhật danh mục thất bại',
  DELETE_CATEGORY_SUCCESS: 'Xóa danh mục thành công',
  DELETE_CATEGORY_FAILURE: 'Xóa danh mục thất bại',
  NAME_IS_REQUIRED: 'Không được bỏ trống tên danh mục',
  NAME_MUST_BE_A_STRING: 'Tên danh mục phải là một chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Tên danh mục phải có độ dài từ 1 đến 100 ký tự',
  INDEX_IS_REQUIRED: 'Không được bỏ trống độ ưu tiên của danh mục',
  INDEX_MUST_BE_A_NUMBER: 'Độ ưu tiên của danh mục phải là một chuỗi ký tự',
  CATEGORY_ID_IS_REQUIRED: 'Không được bỏ trống ID danh mục',
  CATEGORY_ID_MUST_BE_A_STRING: 'ID Danh mục phải là một chuỗi ký tự',
  CATEGORY_ID_IS_MUST_BE_A_ID: 'ID Danh mục không đúng định dạng',
  CATEGORY_ID_DOES_NOT_EXIST: 'ID Danh mục không tồn tại'
}

export const TOPIC_MESSAGE = {
  GET_TOPIC_SUCCESS: 'Lấy thông tin chủ đề thành công',
  GET_TOPIC_FAILURE: 'Lấy thông tin chủ đề thất bại',
  CREATE_TOPIC_SUCCESS: 'Tạo chủ đề thành công',
  CREATE_TOPIC_FAILURE: 'Tạo chủ đề thất bại',
  UPDATE_TOPIC_SUCCESS: 'Cập nhật chủ đề thành công',
  UPDATE_TOPIC_FAILURE: 'Cập nhật chủ đề thất bại',
  DELETE_TOPIC_SUCCESS: 'Xóa chủ đề thành công',
  DELETE_TOPIC_FAILURE: 'Xóa chủ đề thất bại',
  NAME_IS_REQUIRED: 'Không được bỏ trống tên chủ đề',
  NAME_MUST_BE_A_STRING: 'Tên chủ đề phải là một chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Tên chủ đề phải có độ dài từ 1 đến 100 ký tự',
  INDEX_IS_REQUIRED: 'Không được bỏ trống độ ưu tiên của chủ đề',
  INDEX_MUST_BE_A_NUMBER: 'Độ ưu tiên của chủ đề phải là một chuỗi ký tự',
  TOPIC_ID_IS_REQUIRED: 'Không được bỏ trống ID chủ đề',
  TOPIC_ID_MUST_BE_A_STRING: 'ID chủ đề phải là một chuỗi ký tự',
  TOPIC_ID_IS_MUST_BE_A_ID: 'ID chủ đề không đúng định dạng',
  TOPIC_ID_DOES_NOT_EXIST: 'ID chủ đề không tồn tại'
}

export const BRAND_MESSAGE = {
  GET_BRAND_SUCCESS: 'Lấy thông tin thương hiệu thành công',
  GET_BRAND_FAILURE: 'Lấy thông tin thương hiệu thất bại',
  CREATE_BRAND_SUCCESS: 'Tạo thương hiệu thành công',
  CREATE_BRAND_FAILURE: 'Tạo thương hiệu thất bại',
  UPDATE_BRAND_SUCCESS: 'Cập nhật thương hiệu thành công',
  UPDATE_BRAND_FAILURE: 'Cập nhật thương hiệu thất bại',
  DELETE_BRAND_SUCCESS: 'Xóa thương hiệu thành công',
  DELETE_BRAND_FAILURE: 'Xóa thương hiệu thất bại',
  NAME_IS_REQUIRED: 'Không được bỏ trống tên thương hiệu',
  NAME_MUST_BE_A_STRING: 'Tên thương hiệu phải là một chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Tên thương hiệu phải có độ dài từ 1 đến 100 ký tự',
  INDEX_IS_REQUIRED: 'Không được bỏ trống độ ưu tiên của thương hiệu',
  INDEX_MUST_BE_A_NUMBER: 'Độ ưu tiên của thương hiệu phải là một chuỗi ký tự',
  BRAND_ID_IS_REQUIRED: 'Không được bỏ trống ID thương hiệu',
  BRAND_ID_MUST_BE_A_STRING: 'ID thương hiệu phải là một chuỗi ký tự',
  BRAND_ID_IS_MUST_BE_A_ID: 'ID thương hiệu không đúng định dạng',
  BRAND_ID_DOES_NOT_EXIST: 'ID thương hiệu không tồn tại'
}

export const PRODUCT_MESSAGE = {
  GET_PRODUCT_SUCCESS: 'Lấy thông tin sản phẩm thành công',
  GET_PRODUCT_FAILURE: 'Lấy thông tin sản phẩm thất bại',
  CREATE_PRODUCT_SUCCESS: 'Tạo sản phẩm thành công',
  CREATE_PRODUCT_FAILURE: 'Tạo sản phẩm thất bại',
  UPDATE_PRODUCT_SUCCESS: 'Cập nhật sản phẩm thành công',
  UPDATE_PRODUCT_FAILURE: 'Cập nhật sản phẩm thất bại',
  DELETE_PRODUCT_SUCCESS: 'Xóa sản phẩm thành công',
  DELETE_PRODUCT_FAILURE: 'Xóa sản phẩm thất bại',
  TITLE_IS_REQUIRED: 'Không được bỏ trống tên sản phẩm',
  TITLE_MUST_BE_A_STRING: 'Tên sản phẩm phải là một chuỗi ký tự',
  TITLE_LENGTH_MUST_BE_FROM_1_TO_150: 'Tên sản phẩm phải có độ dài từ 1 đến 150 ký tự',
  SUBTITLE_IS_REQUIRED: 'Không được bỏ trống mô tả ngắn sản phẩm',
  SUBTITLE_MUST_BE_A_STRING: 'Mô tả ngắn sản phẩm phải là một chuỗi ký tự',
  SUBTITLE_LENGTH_MUST_BE_FROM_1_TO_300: 'Mô tả ngắn sản phẩm phải có độ dài từ 1 đến 300 ký tự',
  TECHNICAL_INFORMATIONS_MUST_BE_ARRAY: 'Thống số kỹ thuật phải là một mảng',
  TECHNICAL_INFORMATIONS_MUST_BE_AN_ARRAY_AND_HAVE_AT_LEAST_1_PARAMETERS:
    'Thông số kỹ thuật phải là một mảng và phải có nhiều hơn 1 thông số',
  TECHNICAL_INFORMATIONS_MUST_HAVE_IDENTIFICATION_CODE: 'Thông số kỹ thuật phải có một mã định danh',
  TECHNICAL_INFORMATIONS_CODE_IS_REQUIRED: 'Không được bỏ trống mã định danh của thông số kỹ thuật',
  TECHNICAL_INFORMATIONS_CODE_MUST_BE_A_STRING: 'Mã định danh của thông số kỹ thuật phải là một chuổi ký tự',
  TECHNICAL_INFORMATIONS_NAME_IS_REQUIRED: 'Không được bỏ trống tên của thông số kỹ thuật',
  TECHNICAL_INFORMATIONS_NAME_MUST_BE_A_STRING: 'Tên của thông số kỹ thuật phải là một chuổi ký tự',
  TECHNICAL_INFORMATIONS_VALUE_IS_REQUIRED: 'Không được bỏ trống giá trị của thông số kỹ thuật',
  TECHNICAL_INFORMATIONS_VALUE_MUST_BE_A_STRING: 'Giá trị của thông số kỹ thuật phải là một chuổi ký tự',
  TECHNICAL_INFORMATIONS_INDEX_IS_REQUIRED: 'Không được bỏ trống độ ưu tiên của thông số kỹ thuật',
  TECHNICAL_INFORMATIONS_INDEX_MUST_BE_A_NUMBER: 'Độ ưu tiên của thông số kỹ thuật phải là một số',
  FEATURES_MUST_BE_AN_ARRAY_AND_HAVE_AT_LEAST_1_PARAMETERS:
    'Tính năng phải là một mảng và phải có nhiều hơn 1 tính năng',
  FEATURES_VALUE_IS_REQUIRED: 'Không được bỏ trống giá trị của tính năng',
  FEATURES_VALUE_MUST_BE_A_STRING: 'Giá trị của tính năng phải là một chuổi ký tự',
  FEATURES_INDEX_IS_REQUIRED: 'Không được bỏ trống độ ưu tiên của tính năng',
  FEATURES_INDEX_MUST_BE_A_NUMBER: 'Độ ưu tiên của tính năng phải là một số',
  PRICE_IS_REQUIRED: 'Không được bỏ trống giá bán',
  PRICE_MUST_BE_NUMBER_AND_GTE_0: 'Giá bán phải là số và lớn hơn hoặc bằng 0',
  RENT_IS_REQUIRED: 'Không được bỏ trống giá thuê',
  RENT_MUST_BE_NUMBER_AND_GTE_0: 'Giá thuê phải là số và lớn hơn hoặc bằng 0',
  RENT_BY_IS_REQUIRED: 'Không được bỏ trống đơn vị thuê theo',
  RENT_BY_MUST_BE_A_STRING: 'Đơn vị thuê theo phải là một chuỗi ký tự',
  CATEGORY_ID_IS_REQUIRED: 'Không được bỏ trống ID danh mục',
  CATEGORY_ID_MUST_BE_A_STRING: 'ID Danh mục phải là một chuỗi ký tự',
  CATEGORY_ID_IS_MUST_BE_A_ID: 'ID Danh mục không đúng định dạng',
  CATEGORY_ID_DOES_NOT_EXIST: 'ID Danh mục không tồn tại',
  BRAND_ID_IS_REQUIRED: 'Không được bỏ trống ID thương hiệu',
  BRAND_ID_MUST_BE_A_STRING: 'ID thương hiệu phải là một chuỗi ký tự',
  BRAND_ID_IS_MUST_BE_A_ID: 'ID thương hiệu không đúng định dạng',
  BRAND_ID_DOES_NOT_EXIST: 'ID thương hiệu không tồn tại',
  IN_STOCK_IS_REQUIRED: 'Không được bỏ trống trạng thái còn hàng',
  IN_STOCK_MUST_BE_BOOLEAN: 'Trạng thái còn hàng phải là true hoặc false',
  IS_NEW_IS_REQUIRED: 'Không được bỏ trống trạng thái hàng mới',
  IS_NEW_MUST_BE_BOOLEAN: 'Trạng thái hàng mới phải là true hoặc false',
  IS_USED_IS_REQUIRED: 'Không được bỏ trống trạng thái hàng đã qua sử dụng',
  IS_USED_MUST_BE_BOOLEAN: 'Trạng thái hàng đã qua sử dụng phải là true hoặc false',
  PRODUCT_ID_IS_REQUIRED: 'Không được bỏ trống ID sản phẩm',
  PRODUCT_ID_MUST_BE_A_STRING: 'ID sản phẩm phải là một chuỗi ký tự',
  PRODUCT_ID_IS_MUST_BE_A_ID: 'ID sản phẩm không đúng định dạng',
  PRODUCT_ID_DOES_NOT_EXIST: 'ID sản phẩm không tồn tại'
} as const

export const POST_MESSAGE = {
  GET_POST_SUCCESS: 'Lấy thông tin bài viết thành công',
  GET_POST_FAILURE: 'Lấy thông tin bài viết thất bại',
  CREATE_POST_SUCCESS: 'Tạo bài viết thành công',
  CREATE_POST_FAILURE: 'Tạo bài viết thất bại',
  UPDATE_POST_SUCCESS: 'Cập nhật bài viết thành công',
  UPDATE_POST_FAILURE: 'Cập nhật bài viết thất bại',
  DELETE_POST_SUCCESS: 'Xóa bài viết thành công',
  DELETE_POST_FAILURE: 'Xóa bài viết thất bại',
  TITLE_IS_REQUIRED: 'Không được bỏ trống tiêu đề bài viết',
  TITLE_MUST_BE_A_STRING: 'Tiêu đề bài viết phải là một chuỗi ký tự',
  TITLE_LENGTH_MUST_BE_FROM_1_TO_150: 'Tiêu đề bài viết phải có độ dài từ 1 đến 150 ký tự',
  SUBTITLE_IS_REQUIRED: 'Không được bỏ trống mô tả ngắn bài viết',
  SUBTITLE_MUST_BE_A_STRING: 'Mô tả ngắn bài viết phải là một chuỗi ký tự',
  SUBTITLE_LENGTH_MUST_BE_FROM_1_TO_300: 'Mô tả ngắn bài viết phải có độ dài từ 1 đến 300 ký tự',
  CONTENT_IS_REQUIRED: 'Không được bỏ trống nội dung bài viết',
  CONTENT_MUST_BE_A_STRING: 'Nội dung bài viết phải là một chuỗi ký tự',
  CONTENT_LENGTH_MUST_BE_FROM_1_TO_1000000: 'Nội dung bài viết phải có độ dài từ 1 đến 1000000 ký tự',
  TOPIC_ID_IS_REQUIRED: 'Không được bỏ trống ID chủ đề',
  TOPIC_ID_MUST_BE_A_STRING: 'ID chủ đề phải là một chuỗi ký tự',
  TOPIC_ID_IS_MUST_BE_A_ID: 'ID chủ đề không đúng định dạng',
  TOPIC_ID_DOES_NOT_EXIST: 'ID chủ đề không tồn tại',
  IS_FEATURED_IS_REQUIRED: 'Không được bỏ trống bài viết nổi bật',
  IS_FEATURED_MUST_BE_BOOLEAN: 'Bài viết nổi bật phải là true hoặc false',
  POST_ID_IS_REQUIRED: 'Không được bỏ trống ID bài viết',
  POST_ID_MUST_BE_A_STRING: 'ID bài viết phải là một chuỗi ký tự',
  POST_ID_IS_MUST_BE_A_ID: 'ID bài viết không đúng định dạng',
  POST_ID_DOES_NOT_EXIST: 'ID bài viết không tồn tại'
} as const

export const FILE_MANAGEMENT_MESSAGE = {
  IMAGE_IS_REQUIRED: 'Không được bỏ trống hình ảnh',
  UPLOAD_IMAGE_SUCCESS: 'Tải lên hình ảnh thành công',
  UPLOAD_IMAGE_FAILURE: 'Tải lên hình ảnh thất bại'
} as const

export const CONTACT_MESSAGE = {
  GET_CONTACT_SUCCESS: 'Lấy thông tin liên hệ thành công',
  GET_CONTACT_FAILURE: 'Lấy thông tin liên hệ thất bại',
  CONTACT_SUCCESS: 'Để lại thông tin liên hệ thành công',
  CONTACT_FAILURE: 'Để lại thông tin liên hệ thất bại',
  COMPLETE_CONTACT_SUCCESS: 'Hoàn thành liên hệ thành công',
  COMPLETE_CONTACT_FAILURE: 'Hoàn thành liên hệ thất bại',
  NAME_IS_REQUIRED: 'Không được bỏ trống tên của bạn',
  NAME_MUST_BE_A_STRING: 'Tên của bạn phải là chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_50: 'Tên của bạn phải có độ dài từ 1 đến 50 ký tự',
  EMAIL_IS_REQUIRED: 'Không được bỏ trống địa chỉ email',
  EMAIL_MUST_BE_A_STRING: 'Địa chỉ email phải là một chuỗi ký tự',
  EMAIL_LENGTH_MUST_BE_FROM_5_TO_100: 'Địa chỉ email phải có độ dài từ 5 đến 100 ký tự',
  EMAIL_IS_NOT_VALID: 'Địa chỉ email không đúng định dạng',
  PHONE_IS_REQUIRED: 'Không được bỏ trống số điện thoại',
  PHONE_MUST_BE_A_STRING: 'Số điện thoại phải là một chuỗi ký tự',
  PHONE_LENGTH_MUST_BE_FROM_10_TO_11: 'Số điện thoại phải có độ dài từ 10 đến 11 ký tự',
  PHONE_IS_NOT_VALID: 'Số điện thoại không hợp lệ',
  COMPANY_MUST_BE_A_STRING: 'Tên công ty phải là chuỗi ký tự',
  COMPANY_LENGTH_MUST_BE_FROM_1_TO_150: 'Tên công ty phải có độ dài từ 1 đến 150 ký tự',
  TITLE_IS_REQUIRED: 'Không được bỏ trống tiêu đề tin nhắn',
  TITLE_MUST_BE_A_STRING: 'Tiêu đề tin nhắn phải là một chuỗi ký tự',
  TITLE_LENGTH_MUST_BE_FROM_1_TO_150: 'Tiêu đề tin nhắn phải có độ dài từ 1 đến 150 ký tự',
  CONTENT_IS_REQUIRED: 'Không được bỏ trống Nội dung tinh nhắn',
  CONTENT_MUST_BE_A_STRING: 'Nội dung tinh nhắn phải là một chuỗi ký tự',
  CONTENT_LENGTH_MUST_BE_FROM_1_TO_1000: 'Nội dung tinh nhắn phải có độ dài từ 1 đến 1000 ký tự',
  CONTACT_ID_IS_REQUIRED: 'Không được bỏ trống ID liên hệ',
  CONTACT_ID_MUST_BE_A_STRING: 'ID liên hệ phải là một chuỗi ký tự',
  CONTACT_ID_IS_MUST_BE_A_ID: 'ID liên hệ không đúng định dạng',
  CONTACT_ID_DOES_NOT_EXIST: 'ID liên hệ không tồn tại'
} as const
