export const RESPONSE_CODE = {
  SERVER_SIDE_ERROR: 'SERVER_SIDE_ERROR',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  FATAL_AUTHENTICATION_FAILURE: 'FATAL_AUTHENTICATION_FAILURE',
  INPUT_DATA_ERROR: 'INPUT_DATA_ERROR',
  FATAL_INPUT_ERROR: 'FATAL_INPUTERROR',
  REGISTER_SUCCESSFUL: 'REGISTER_SUCCESSFUL',
  REGISTER_FAILED: 'REGISTER_FAILED',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  TOKEN_VERIFICATION_SUCCESSFUL: 'TOKEN_VERIFICATION_SUCCESSFUL',
  TOKEN_AUTHENTICATION_SUCCESSFUL_TOKEN_CHANGED: 'TOKEN_AUTHENTICATION_SUCCESSFUL_TOKEN_CHANGED',
  TOKEN_VERIFICATION_FAILED: 'TOKEN_VERIFICATION_FAILED'
} as const
